#!/bin/bash

#Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
	echo "Error:PYFILE environment variable is not set."
	exit 1
fi

#Run the Python Script using the filename from the PYFILE variable
exec python3 "$PYFILE"  
